Solved the backslash issue
myint/scspell pull request #31
Opened 2018-10-27 02:16 UTC by dhruvsomani

The backslash issue has been solved. Now the program considers both the words, including and not including the leading character as possible words and if even one of them passes the checks, removed from the warnings list.

2018-10-27 02:25 UTC, andrewda requested changes

2018-10-27 02:25 UTC, andrewda commented on scspell/__init__.py
> +
Try to keep unrelated style changes to a minimum.

2018-10-27 02:25 UTC, andrewda commented on scspell/__init__.py
> +
^

2018-10-27 02:25 UTC, andrewda commented on scspell/__init__.py
> +        ]
^

2018-10-27 02:43 UTC, andrewda approved these changes

2018-10-27 03:23 UTC, jayvdb requested changes

2018-10-27 03:23 UTC, jayvdb commented on scspell/__init__.py
> +            if (with_next or without_next):
round brackets not needed here

2018-10-27 03:23 UTC, jayvdb commented on scspell/__init__.py
> +        if (len(unmatched_subtokens) > 0) and \
round brackets used correctly here, but line_continuation `\` isnt needed inside round brackets

2018-10-27 03:23 UTC, jayvdb commented on scspell/__init__.py
> +            with_next = (len(st[1:]) <= LEN_THRESHOLD) or \
replace the line continuation `\` with round brackets.  i.e use `with_next = ((...)\n(...)\n(...))`  - where `\n` means a real EOL and appropriate indentation, not `\` + `n` and bad indentation ;-)

same with `without_next` below.

2018-10-27 03:23 UTC, jayvdb commented on scspell/__init__.py
> +# C_ESCAPE_TOKEN_REGEX = re.compile(r'(?<![^\\]\\)\w+')
remove this comment

2018-10-27 03:23 UTC, jayvdb commented on scspell/__init__.py
>  # immediately preceded by a single backslash.  (The string "\ntext" should
this comment needs to be rewritten to explain your new improved algorithm

2018-11-04 16:18 UTC, myint requested changes
Cool!

Can you add some test cases to `test.cram`. `cram` isn't very well known so below is an example. You can either [install](https://pypi.org/project/cram/) it and run `cram --indent=4 test.cram` or you can just let Jenkins run the test.

```diff
diff --git a/test.cram b/test.cram
index 854fe3a..0718fa5 100755
--- a/test.cram
+++ b/test.cram
@@ -16,6 +16,18 @@ Test okay file.
     $ echo 'This is okay.' > good.txt
     $ $SCSPELL good.txt

+Test spelling mistake with backslashes.
+
+    $ echo '\ethis is okay.' > good.txt
+    $ $SCSPELL good.txt
+
+Test okay file with backslashes.
+
+    $ echo '\ethiss is a mistake.' > bad.txt
+    $ $SCSPELL bad.txt
+    bad.txt:1: 'ethiss' not found in dictionary (from token 'ethiss')
+    [1]
+

 Test file with --override-dictionary and a fileid mapping entry
```

2018-11-08 17:05 UTC, dhruvsomani commented
@myint Sorry for the late reply. I tried running the command you told and I get an error:
<details>
```
    #!/usr/bin/env cram --indent=4

    Test scspell.

      $ SCSPELL="python $TESTDIR --report-only"

    Test spelling mistake.

      $ echo 'This is blabbb.' > bad.txt
      $ $SCSPELL bad.txt
      usage: scspell [-h] [--report-only] [--no-c-escapes] [--list-unique]
                     [--override-dictionary FILE] [--set-dictionary FILE]
                     [--export-dictionary FILE] [--base-dict BASE_DICT]
                     [--use-builtin-base-dict] [--filter-out-base-dicts]
                     [--relative-to RELATIVE_TO] [-i]
                     [--merge-file-ids FROM_ID TO_ID]
                     [--copy-file FROM_FILE TO_FILE]
                     [--rename-file FROM_FILE TO_FILE] [--delete-files]
                     [--add-to-dict DICT_TYPE WORD] [-D] [--version]
                     [files [files ...]]
      scspell: error: unrecognized arguments: --report-only\r (esc)
      [2]

    Test okay file.

      $ echo 'This is okay.' > good.txt
      $ $SCSPELL good.txt
      usage: scspell [-h] [--report-only] [--no-c-escapes] [--list-unique]
                     [--override-dictionary FILE] [--set-dictionary FILE]
                     [--export-dictionary FILE] [--base-dict BASE_DICT]
                     [--use-builtin-base-dict] [--filter-out-base-dicts]
                     [--relative-to RELATIVE_TO] [-i]
                     [--merge-file-ids FROM_ID TO_ID]
                     [--copy-file FROM_FILE TO_FILE]
                     [--rename-file FROM_FILE TO_FILE] [--delete-files]
                     [--add-to-dict DICT_TYPE WORD] [-D] [--version]
                     [files [files ...]]
      scspell: error: unrecognized arguments: --report-only\r (esc)
      [2]


    Test file with --override-dictionary and a fileid mapping entry

      $ cp -a "$TESTDIR/tests" .
      $ $SCSPELL --override-dictionary 'tests/fileidmap/dictionary' \
      >     --relative-to 'tests/fileidmap' \
      >     'tests/fileidmap/inputfile.txt' 'tests/fileidmap/inputfile2.txt'
      usage: scspell [-h] [--report-only] [--no-c-escapes] [--list-unique]
                     [--override-dictionary FILE] [--set-dictionary FILE]
                     [--export-dictionary FILE] [--base-dict BASE_DICT]
                     [--use-builtin-base-dict] [--filter-out-base-dicts]
                     [--relative-to RELATIVE_TO] [-i]
                     [--merge-file-ids FROM_ID TO_ID]
                     [--copy-file FROM_FILE TO_FILE]
                     [--rename-file FROM_FILE TO_FILE] [--delete-files]
                     [--add-to-dict DICT_TYPE WORD] [-D] [--version]
                     [files [files ...]]
      scspell: error: unrecognized arguments: --report-only\r (esc)
      /bin/sh: 15: --relative-to: not found
      /bin/sh: 16: tests/fileidmap/inputfile.txt: not found
      [127]

    Test file ID manipulations

      $ $SCSPELL --override-dictionary tests/fileidmap/dictionary \
      >     --relative-to tests/fileidmap \
      >     tests/fileidmap/mix*
      usage: scspell [-h] [--report-only] [--no-c-escapes] [--list-unique]
                     [--override-dictionary FILE] [--set-dictionary FILE]
                     [--export-dictionary FILE] [--base-dict BASE_DICT]
                     [--use-builtin-base-dict] [--filter-out-base-dicts]
                     [--relative-to RELATIVE_TO] [-i]
                     [--merge-file-ids FROM_ID TO_ID]
                     [--copy-file FROM_FILE TO_FILE]
                     [--rename-file FROM_FILE TO_FILE] [--delete-files]
                     [--add-to-dict DICT_TYPE WORD] [-D] [--version]
                     [files [files ...]]
      scspell: error: unrecognized arguments: --report-only\r (esc)
      /bin/sh: 19: --relative-to: not found
      /bin/sh: 20: tests/fileidmap/mix*\r (no-eol) (esc)
      : not found
      [127]
      $ $SCSPELL --override-dictionary tests/fileidmap/dictionary \
      >     --relative-to tests/fileidmap \
      >     --merge-file-ids tests/fileidmap/mix4.txt tests/fileidmap/mix1.txt
      usage: scspell [-h] [--report-only] [--no-c-escapes] [--list-unique]
                     [--override-dictionary FILE] [--set-dictionary FILE]
                     [--export-dictionary FILE] [--base-dict BASE_DICT]
                     [--use-builtin-base-dict] [--filter-out-base-dicts]
                     [--relative-to RELATIVE_TO] [-i]
                     [--merge-file-ids FROM_ID TO_ID]
                     [--copy-file FROM_FILE TO_FILE]
                     [--rename-file FROM_FILE TO_FILE] [--delete-files]
                     [--add-to-dict DICT_TYPE WORD] [-D] [--version]
                     [files [files ...]]
      scspell: error: unrecognized arguments: --report-only\r (esc)
      /bin/sh: 23: --relative-to: not found
      /bin/sh: 24: --merge-file-ids: not found
      [127]
      $ mv tests/fileidmap/mix2.txt tests/fileidmap/mix22.txt
      mv: cannot stat 'tests/fileidmap/mix2.txt': No such file or directory
      [1]
      $ $SCSPELL --override-dictionary tests/fileidmap/dictionary \
      >     --relative-to tests/fileidmap \
      >     --rename-file tests/fileidmap/mix2.txt tests/fileidmap/mix22.txt
      usage: scspell [-h] [--report-only] [--no-c-escapes] [--list-unique]
                     [--override-dictionary FILE] [--set-dictionary FILE]
                     [--export-dictionary FILE] [--base-dict BASE_DICT]
                     [--use-builtin-base-dict] [--filter-out-base-dicts]
                     [--relative-to RELATIVE_TO] [-i]
                     [--merge-file-ids FROM_ID TO_ID]
                     [--copy-file FROM_FILE TO_FILE]
                     [--rename-file FROM_FILE TO_FILE] [--delete-files]
                     [--add-to-dict DICT_TYPE WORD] [-D] [--version]
                     [files [files ...]]
      scspell: error: unrecognized arguments: --report-only\r (esc)
      /bin/sh: 29: --relative-to: not found
      /bin/sh: 30: --rename-file: not found
      [127]
      $ $SCSPELL --override-dictionary tests/fileidmap/dictionary \
      >     --relative-to tests/fileidmap \
      >     --delete-file tests/fileidmap/mix5.txt
      usage: scspell [-h] [--report-only] [--no-c-escapes] [--list-unique]
                     [--override-dictionary FILE] [--set-dictionary FILE]
                     [--export-dictionary FILE] [--base-dict BASE_DICT]
                     [--use-builtin-base-dict] [--filter-out-base-dicts]
                     [--relative-to RELATIVE_TO] [-i]
                     [--merge-file-ids FROM_ID TO_ID]
                     [--copy-file FROM_FILE TO_FILE]
                     [--rename-file FROM_FILE TO_FILE] [--delete-files]
                     [--add-to-dict DICT_TYPE WORD] [-D] [--version]
                     [files [files ...]]
      scspell: error: unrecognized arguments: --report-only\r (esc)
      /bin/sh: 33: --relative-to: not found
      /bin/sh: 34: --delete-file: not found
      [127]
      $ $SCSPELL --override-dictionary tests/fileidmap/dictionary \
      >     --relative-to tests/fileidmap \
      >     --copy-file tests/fileidmap/mix3.txt tests/fileidmap/mix33.txt
      usage: scspell [-h] [--report-only] [--no-c-escapes] [--list-unique]
                     [--override-dictionary FILE] [--set-dictionary FILE]
                     [--export-dictionary FILE] [--base-dict BASE_DICT]
                     [--use-builtin-base-dict] [--filter-out-base-dicts]
                     [--relative-to RELATIVE_TO] [-i]
                     [--merge-file-ids FROM_ID TO_ID]
                     [--copy-file FROM_FILE TO_FILE]
                     [--rename-file FROM_FILE TO_FILE] [--delete-files]
                     [--add-to-dict DICT_TYPE WORD] [-D] [--version]
                     [files [files ...]]
      scspell: error: unrecognized arguments: --report-only\r (esc)
      /bin/sh: 37: --relative-to: not found
    [...]

2018-11-09 14:18 UTC, myint commented
@dhruvsomani Not sure what that failure is about. Perhaps `cram` has some platform-specific issues. I'll just add it after merging.

2018-11-09 14:18 UTC, myint approved these changes

2018-11-09 14:18 UTC, merged

2018-11-09 14:25 UTC, myint commented
Actually, I had to revert this. I noticed a bug after merging:

```
$ python -m scspell setup.py
setup.py:8: Unmatched 'get_version' --> {get_version}
   (i)gnore, (I)gnore all, (r)eplace, (R)eplace all, (a)dd to dictionary, or
   show (c)ontext? [i]
```

If this pull request is merged in, `scspell` stops properly splitting at `_`. Note that before this "get_version" was properly split into "get" and "version" which are in the dictionary.